# Generated by Django 5.1.5 on 2025-01-15 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('vehicle_info', models.JSONField(default='', null=True, verbose_name='VehicleInfo')),
                ('subscriber_info', models.JSONField(default='', null=True, verbose_name='SubscriberInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usermodel', verbose_name='user_subscription')),
            ],
        ),
    ]
