# Generated by Django 5.1.5 on 2025-01-15 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garantee', '0001_initial'),
        ('simulation', '0001_initial'),
        ('subscription', '0001_initial'),
        ('vehicleCategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('categories', models.ManyToManyField(to='vehicleCategory.vehiclecategorymodel', verbose_name='vehicleCategory_product_id')),
                ('guarantees', models.ManyToManyField(to='garantee.garanteemodel', verbose_name='garantee_product_id')),
                ('simulation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.simulationmodel', verbose_name='simulation_product_id')),
                ('subcription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionmodel', verbose_name='subscription_product_id')),
            ],
        ),
    ]
