# Generated by Django 5.1.5 on 2025-01-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaranteeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('rate', models.FloatField()),
                ('min_premium', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
